ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#757575"


ZSH_HIGHLIGHT_STYLES[command]="fg=#dbad14"
ZSH_HIGHLIGHT_STYLES[arg0]="fg=#dbad14"
ZSH_HIGHLIGHT_STYLES[default]="none"
ZSH_HIGHLIGHT_STYLES[path]="fg=#c78640"
